import { MachineModel, MachineType } from "./types";

export const LOAD_FACTORS = {
  [MachineType.NEUMATICO]: {
    Excelente: 0.25,
    Promedio: 0.3,
    Severo: 0.4,
  },
  [MachineType.ORUGA]: {
    Excelente: 0.5,
    Promedio: 0.65,
    Severo: 0.75,
  },
};

export const MATERIAL_DESCRIPTIONS = {
  [MachineType.NEUMATICO]: {
    Excelente:
      "tierra suelta, arena, agregados, escoria, relaves, arcilla suelta, etc",
    Promedio:
      "tierra con rocas, arena con rocas, agregados con piedras, arcilla con roca, etc",
    Severo:
      "roca de voladura bancos para rellenos de cimentación, desmonte de concreto",
  },
  [MachineType.ORUGA]: {
    Excelente:
      "tierra suelta, arena, agregados, escoria, relaves, arcilla suelta, etc",
    Promedio:
      "tierra con rocas, arena con rocas, agregados con piedras, arcilla con roca, etc",
    Severo:
      "roca de voladura bancos para rellenos de cimentación, desmonte de concreto",
  },
};

export const MACHINERY_DATA: MachineModel[] = [
  // ===== CARGADOR FRONTAL =====
  {
    id: "1",
    category: "Cargador Frontal",
    model: "WA150PZ-6",
    hp: 98,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "2",
    category: "Cargador Frontal",
    model: "WA200PZ-6",
    hp: 126,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "3",
    category: "Cargador Frontal",
    model: "WA250PZ-6",
    hp: 138,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "4",
    category: "Cargador Frontal",
    model: "WA320-6",
    hp: 167,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "5",
    category: "Cargador Frontal",
    model: "WA380-7",
    hp: 191,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "6",
    category: "Cargador Frontal",
    model: "WA430-6",
    hp: 231,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "7",
    category: "Cargador Frontal",
    model: "WA470-6",
    hp: 272,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "8",
    category: "Cargador Frontal",
    model: "WA480-6",
    hp: 299,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "9",
    category: "Cargador Frontal",
    model: "WA500-6",
    hp: 353,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "10",
    category: "Cargador Frontal",
    model: "L50E",
    hp: 98,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "11",
    category: "Cargador Frontal",
    model: "L60F",
    hp: 154,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "12",
    category: "Cargador Frontal",
    model: "L110F",
    hp: 227,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "13",
    category: "Cargador Frontal",
    model: "966H",
    hp: 262,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  }, // 262 HP es el estándar neto SAE J1349
  {
    id: "33",
    category: "Cargador Frontal",
    model: "WA600-8",
    hp: 529,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "34",
    category: "Cargador Frontal",
    model: "950GC",
    hp: 225,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "35",
    category: "Cargador Frontal",
    model: "980H",
    hp: 349,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "36",
    category: "Cargador Frontal",
    model: "L120H",
    hp: 272,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "54",
    category: "Cargador Frontal",
    model: "950M",
    hp: 230,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "55",
    category: "Cargador Frontal",
    model: "WA470-8",
    hp: 272,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "56",
    category: "Cargador Frontal",
    model: "L90H",
    hp: 184,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "57",
    category: "Cargador Frontal",
    model: "544L",
    hp: 163,
    type: MachineType.NEUMATICO,
    brand: "JOHN_DEERE",
  },
  {
    id: "58",
    category: "Cargador Frontal",
    model: "HL757-9",
    hp: 197,
    type: MachineType.NEUMATICO,
    brand: "HYUNDAI",
  },
  {
    id: "59",
    category: "Cargador Frontal",
    model: "DL300-5",
    hp: 271,
    type: MachineType.NEUMATICO,
    brand: "DOOSAN",
  },
  {
    id: "60",
    category: "Cargador Frontal",
    model: "437ZX",
    hp: 173,
    type: MachineType.NEUMATICO,
    brand: "JCB",
  },
  {
    id: "78",
    category: "Cargador Frontal",
    model: "WA200PZ-6 (PDF)",
    hp: 127,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },

  // ===== TRACTOR ORUGA =====
  {
    id: "14",
    category: "Tractor Oruga",
    model: "D31EX-22",
    hp: 78,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "15",
    category: "Tractor Oruga",
    model: "D61EX-15E0",
    hp: 168,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "16",
    category: "Tractor Oruga",
    model: "D155AX-6",
    hp: 354,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "17",
    category: "Tractor Oruga",
    model: "D8T",
    hp: 310,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "18",
    category: "Tractor Oruga",
    model: "D11T",
    hp: 850,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "42",
    category: "Tractor Oruga",
    model: "D6T",
    hp: 200,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "43",
    category: "Tractor Oruga",
    model: "D7E",
    hp: 235,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "44",
    category: "Tractor Oruga",
    model: "D85EX-15",
    hp: 264,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "68",
    category: "Tractor Oruga",
    model: "D6K2",
    hp: 130,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "69",
    category: "Tractor Oruga",
    model: "D65EX-16",
    hp: 219,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },

  // ===== EXCAVADORA =====
  {
    id: "19",
    category: "Excavadora",
    model: "PC200LC-8",
    hp: 148,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "20",
    category: "Excavadora",
    model: "PC350LC-8",
    hp: 246,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "21",
    category: "Excavadora",
    model: "320C L",
    hp: 138,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  }, // Confirmado 138 HP Neto para motor 3066 T
  {
    id: "22",
    category: "Excavadora",
    model: "EC210B",
    hp: 145,
    type: MachineType.ORUGA,
    brand: "VOLVO",
  },
  {
    id: "23",
    category: "Excavadora",
    model: "PC2000-8",
    hp: 976,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "37",
    category: "Excavadora",
    model: "PC300LC-8",
    hp: 246,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "38",
    category: "Excavadora",
    model: "PC400LC-8",
    hp: 345,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "39",
    category: "Excavadora",
    model: "336D",
    hp: 268,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "40",
    category: "Excavadora",
    model: "349D",
    hp: 380,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "41",
    category: "Excavadora",
    model: "EC480D",
    hp: 343,
    type: MachineType.ORUGA,
    brand: "VOLVO",
  },
  {
    id: "61",
    category: "Excavadora",
    model: "330D2",
    hp: 208,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "62",
    category: "Excavadora",
    model: "PC210LC-11",
    hp: 165,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "63",
    category: "Excavadora",
    model: "EC300D",
    hp: 227,
    type: MachineType.ORUGA,
    brand: "VOLVO",
  },
  {
    id: "64",
    category: "Excavadora",
    model: "350G LC",
    hp: 271,
    type: MachineType.ORUGA,
    brand: "JOHN_DEERE",
  },
  {
    id: "65",
    category: "Excavadora",
    model: "HX300L",
    hp: 242,
    type: MachineType.ORUGA,
    brand: "HYUNDAI",
  },
  {
    id: "66",
    category: "Excavadora",
    model: "DX300LC-5",
    hp: 271,
    type: MachineType.ORUGA,
    brand: "DOOSAN",
  },
  {
    id: "67",
    category: "Excavadora",
    model: "JS220LC",
    hp: 173,
    type: MachineType.ORUGA,
    brand: "JCB",
  },
  {
    id: "78",
    category: "Excavadora",
    model: "DX300LCA",
    hp: 197,
    type: MachineType.ORUGA,
    brand: "DOOSAN",
  }, // Verificado: 197 HP Neto

  // ===== RETROEXCAVADORA =====
  {
    id: "24",
    category: "Retroexcavadora",
    model: "416D",
    hp: 74,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "25",
    category: "Retroexcavadora",
    model: "WB93R-5",
    hp: 98,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "26",
    category: "Retroexcavadora",
    model: "BL 70",
    hp: 90,
    type: MachineType.NEUMATICO,
    brand: "JCB",
  },
  {
    id: "48",
    category: "Retroexcavadora",
    model: "420F2",
    hp: 93,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "49",
    category: "Retroexcavadora",
    model: "3CX",
    hp: 91,
    type: MachineType.NEUMATICO,
    brand: "JCB",
  },
  {
    id: "50",
    category: "Retroexcavadora",
    model: "310SL",
    hp: 99,
    type: MachineType.NEUMATICO,
    brand: "JOHN_DEERE",
  },
  {
    id: "73",
    category: "Retroexcavadora",
    model: "422F2",
    hp: 101,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "74",
    category: "Retroexcavadora",
    model: "WB97R-5",
    hp: 98,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "75",
    category: "Retroexcavadora",
    model: "4CX",
    hp: 109,
    type: MachineType.NEUMATICO,
    brand: "JCB",
  },

  // ===== MOTONIVELADORA =====
  {
    id: "27",
    category: "Motoniveladora",
    model: "GD555-3A",
    hp: 160,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "28",
    category: "Motoniveladora",
    model: "G930",
    hp: 160,
    type: MachineType.NEUMATICO,
    brand: "JOHN_DEERE",
  }, // G930 Neto base es 160 HP
  {
    id: "29",
    category: "Motoniveladora",
    model: "140M",
    hp: 183,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "45",
    category: "Motoniveladora",
    model: "GD655-5",
    hp: 218,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "46",
    category: "Motoniveladora",
    model: "120K",
    hp: 145,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "47",
    category: "Motoniveladora",
    model: "12K",
    hp: 145,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "70",
    category: "Motoniveladora",
    model: "140K",
    hp: 170,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "71",
    category: "Motoniveladora",
    model: "GD655-7",
    hp: 218,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "72",
    category: "Motoniveladora",
    model: "670G",
    hp: 217,
    type: MachineType.NEUMATICO,
    brand: "JOHN_DEERE",
  },

  // ===== CAMION VOLQUETE =====
  {
    id: "30",
    category: "Camion Volquete",
    model: "770",
    hp: 476,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "31",
    category: "Camion Volquete",
    model: "777F",
    hp: 938,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "32",
    category: "Camion Volquete",
    model: "797F",
    hp: 3793,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "51",
    category: "Camion Volquete",
    model: "785C",
    hp: 1348,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "52",
    category: "Camion Volquete",
    model: "793F",
    hp: 2419,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "53",
    category: "Camion Volquete",
    model: "HD785-7",
    hp: 1178,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "76",
    category: "Camion Volquete",
    model: "730C",
    hp: 367,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "77",
    category: "Camion Volquete",
    model: "HM400-5",
    hp: 469,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },

  // ===== NUEVOS MODELOS DESDE PDF =====
  // Cargadores Frontales adicionales
  {
    id: "79",
    category: "Cargador Frontal",
    model: "WA600-6",
    hp: 531,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "80",
    category: "Cargador Frontal",
    model: "WA800-3",
    hp: 853,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "81",
    category: "Cargador Frontal",
    model: "WA900-3",
    hp: 901,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "82",
    category: "Cargador Frontal",
    model: "WA1200-6",
    hp: 1762,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "83",
    category: "Cargador Frontal",
    model: "L70F",
    hp: 169,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "84",
    category: "Cargador Frontal",
    model: "L90F",
    hp: 173,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "85",
    category: "Cargador Frontal",
    model: "L120F",
    hp: 241,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "86",
    category: "Cargador Frontal",
    model: "L150F",
    hp: 281,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "87",
    category: "Cargador Frontal",
    model: "L180F",
    hp: 315,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "88",
    category: "Cargador Frontal",
    model: "L220F",
    hp: 350,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "89",
    category: "Cargador Frontal",
    model: "L350F",
    hp: 532,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "90",
    category: "Cargador Frontal",
    model: "924G",
    hp: 121,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "91",
    category: "Cargador Frontal",
    model: "938G",
    hp: 160,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "92",
    category: "Cargador Frontal",
    model: "950H",
    hp: 196,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "93",
    category: "Cargador Frontal",
    model: "980H (PDF Version)",
    hp: 318,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "94",
    category: "Cargador Frontal",
    model: "994F",
    hp: 1577,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },

  // Tractores Oruga adicionales
  {
    id: "95",
    category: "Tractor Oruga",
    model: "D37EX-22",
    hp: 80,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "96",
    category: "Tractor Oruga",
    model: "D39EX-22",
    hp: 105,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "97",
    category: "Tractor Oruga",
    model: "D51EX-15E0",
    hp: 130,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "98",
    category: "Tractor Oruga",
    model: "D51PX-22",
    hp: 130,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "99",
    category: "Tractor Oruga",
    model: "D275AX-5E0",
    hp: 449,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "100",
    category: "Tractor Oruga",
    model: "D3G XL",
    hp: 70,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "101",
    category: "Tractor Oruga",
    model: "D4G XL",
    hp: 80,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "102",
    category: "Tractor Oruga",
    model: "D5G XL",
    hp: 90,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "103",
    category: "Tractor Oruga",
    model: "D6N XL",
    hp: 145,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "104",
    category: "Tractor Oruga",
    model: "D6R Series II",
    hp: 185,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "105",
    category: "Tractor Oruga",
    model: "D7R Series II",
    hp: 240,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "106",
    category: "Tractor Oruga",
    model: "D8R Series II",
    hp: 310,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "107",
    category: "Tractor Oruga",
    model: "D9R / D9T",
    hp: 410,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "108",
    category: "Tractor Oruga",
    model: "D10T",
    hp: 580,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },

  // Motoniveladoras adicionales
  {
    id: "109",
    category: "Motoniveladora",
    model: "GD511A-1",
    hp: 135,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "110",
    category: "Motoniveladora",
    model: "GD655-3E0",
    hp: 190,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "111",
    category: "Motoniveladora",
    model: "GD675-3E0",
    hp: 200,
    type: MachineType.NEUMATICO,
    brand: "KOMATSU",
  },
  {
    id: "112",
    category: "Motoniveladora",
    model: "G940",
    hp: 215,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "113",
    category: "Motoniveladora",
    model: "G946",
    hp: 235,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "114",
    category: "Motoniveladora",
    model: "G960",
    hp: 235,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "115",
    category: "Motoniveladora",
    model: "G970",
    hp: 250,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "116",
    category: "Motoniveladora",
    model: "G976",
    hp: 265,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "117",
    category: "Motoniveladora",
    model: "G990",
    hp: 265,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "118",
    category: "Motoniveladora",
    model: "120H",
    hp: 125,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "119",
    category: "Motoniveladora",
    model: "12H",
    hp: 140,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "120",
    category: "Motoniveladora",
    model: "120M",
    hp: 153,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "121",
    category: "Motoniveladora",
    model: "140H",
    hp: 165,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "122",
    category: "Motoniveladora",
    model: "14M",
    hp: 274,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "123",
    category: "Motoniveladora",
    model: "16H",
    hp: 275,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "124",
    category: "Motoniveladora",
    model: "16M",
    hp: 332,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "125",
    category: "Motoniveladora",
    model: "24H",
    hp: 500,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "126",
    category: "Motoniveladora",
    model: "24M",
    hp: 533,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },

  // Retroexcavadoras adicionales
  {
    id: "127",
    category: "Retroexcavadora",
    model: "416E",
    hp: 76,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "128",
    category: "Retroexcavadora",
    model: "416F",
    hp: 87,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "129",
    category: "Retroexcavadora",
    model: "420D",
    hp: 88,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "130",
    category: "Retroexcavadora",
    model: "420E",
    hp: 89,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "131",
    category: "Retroexcavadora",
    model: "420F",
    hp: 92,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "132",
    category: "Retroexcavadora",
    model: "430D",
    hp: 94,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "133",
    category: "Retroexcavadora",
    model: "430E",
    hp: 97,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "134",
    category: "Retroexcavadora",
    model: "430F",
    hp: 107,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "135",
    category: "Retroexcavadora",
    model: "450F",
    hp: 128,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "136",
    category: "Retroexcavadora",
    model: "BL60",
    hp: 83,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },

  // Excavadoras adicionales
  {
    id: "137",
    category: "Excavadora",
    model: "PC88MR-8",
    hp: 66,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "138",
    category: "Excavadora",
    model: "PC130-8",
    hp: 96,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "139",
    category: "Excavadora",
    model: "PC160LC-8",
    hp: 121,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "140",
    category: "Excavadora",
    model: "PC190LC-8",
    hp: 130,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "141",
    category: "Excavadora",
    model: "PC210-8",
    hp: 156,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "142",
    category: "Excavadora",
    model: "PC210LC-10",
    hp: 165,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "143",
    category: "Excavadora",
    model: "PC240LC-10",
    hp: 189,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "144",
    category: "Excavadora",
    model: "PC290LC-10",
    hp: 213,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "145",
    category: "Excavadora",
    model: "PC360LC-10",
    hp: 275,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "146",
    category: "Excavadora",
    model: "PC490/LC-10",
    hp: 362,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "147",
    category: "Excavadora",
    model: "PC600/LC-8",
    hp: 433,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "148",
    category: "Excavadora",
    model: "PC700LC-8",
    hp: 433,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "149",
    category: "Excavadora",
    model: "PC800/LC-8",
    hp: 496,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "150",
    category: "Excavadora",
    model: "PC1250/SP-8",
    hp: 691,
    type: MachineType.ORUGA,
    brand: "KOMATSU",
  },
  {
    id: "151",
    category: "Excavadora",
    model: "301.6C",
    hp: 18.1,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "152",
    category: "Excavadora",
    model: "303C CR",
    hp: 30,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "153",
    category: "Excavadora",
    model: "305C CR",
    hp: 47,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "154",
    category: "Excavadora",
    model: "307C",
    hp: 54,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "155",
    category: "Excavadora",
    model: "312C L",
    hp: 90,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "156",
    category: "Excavadora",
    model: "315C L",
    hp: 110,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "157",
    category: "Excavadora",
    model: "325D L",
    hp: 204,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "158",
    category: "Excavadora",
    model: "330D L",
    hp: 268,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "159",
    category: "Excavadora",
    model: "345C L",
    hp: 345,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "160",
    category: "Excavadora",
    model: "365C L",
    hp: 404,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "161",
    category: "Excavadora",
    model: "385C L",
    hp: 513,
    type: MachineType.ORUGA,
    brand: "CATERPILLAR",
  },
  {
    id: "162",
    category: "Excavadora",
    model: "EC360B",
    hp: 250,
    type: MachineType.ORUGA,
    brand: "VOLVO",
  },
  {
    id: "163",
    category: "Excavadora",
    model: "EC460B",
    hp: 316,
    type: MachineType.ORUGA,
    brand: "VOLVO",
  },

  // Camiones Volquete y Articulados
  {
    id: "164",
    category: "Camion Volquete",
    model: "772",
    hp: 535,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "165",
    category: "Camion Volquete",
    model: "785D",
    hp: 1348,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "166",
    category: "Camion Volquete",
    model: "789C",
    hp: 1771,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "167",
    category: "Camion Articulado",
    model: "740",
    hp: 415,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "168",
    category: "Camion Articulado",
    model: "A35F",
    hp: 441,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },
  {
    id: "169",
    category: "Camion Articulado",
    model: "A40F",
    hp: 469,
    type: MachineType.NEUMATICO,
    brand: "VOLVO",
  },

  // Rodillos
  {
    id: "170",
    category: "Rodillo",
    model: "CS-433E",
    hp: 101,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "171",
    category: "Rodillo",
    model: "CS-563D",
    hp: 153,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "172",
    category: "Rodillo",
    model: "CS-663E",
    hp: 180,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "173",
    category: "Rodillo",
    model: "CB-214D",
    hp: 31,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "174",
    category: "Rodillo",
    model: "CB-534C",
    hp: 105,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
  {
    id: "175",
    category: "Rodillo",
    model: "CB-634D",
    hp: 145,
    type: MachineType.NEUMATICO,
    brand: "CATERPILLAR",
  },
];
